server:
  port: 8080

spring:
  application:
    name: doc-manager-web
  datasource:
    url: jdbc:sqlite:${doc-manager.db-dir}/${database.name}.db?foreign_keys=on
    driver-class-name: org.sqlite.JDBC
  # 配置flyway
  flyway:
    enabled: true
    locations: classpath:flyway/migration

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.szr.docmanagerweb.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

database:
  name: doc-manager

doc-manager:
  db-dir: ${user.home}/doc-manager/db
